version: '3.1'
services:
  draco:
    image: ging/fiware-draco:2.1.0
    container_name: draco
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
    ports:
      - "8443:8443"
      # - "9090:9090"
      # - "8080:8080"
      # - "5050:5050"
    volumes:
        # - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
        # - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
        # - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
        # - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
        # - ./nifi/state:/opt/nifi/nifi-current/state
        - .\nifi\logs:/opt/nifi/nifi-current/logs
        # - ./nifi/lib:/opt/nifi/nifi-current/lib 
  # db-mysql:
  #   image: mysql:5.7.22
  #   container_name: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #     environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     ports:
  #     - "3306:3306"
 # db-postgres:
  #  image: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_PASSWORD: example
  #  ports:
  #    - "5432:5432"
  # mongo-db:
  #   image: mongo:3.4
  #   restart: always
  #     ports:
  #     - "27017:27017"
  # db-cassandra:
  #   image: cassandra
  #   restart: always
  #      ports:
  #     - "9042:9042"
